// Code generated by "stringer -type=Kind -trimprefix=Error"; DO NOT EDIT.

package filesystem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorOther-0]
	_ = x[ErrorInvalidItem-1]
	_ = x[ErrorInvalidOperation-2]
	_ = x[ErrorPermission-3]
	_ = x[ErrorIO-4]
	_ = x[ErrorExist-5]
	_ = x[ErrorNotExist-6]
	_ = x[ErrorIsDir-7]
	_ = x[ErrorNotDir-8]
	_ = x[ErrorNotEmpty-9]
	_ = x[ErrorReadOnly-10]
}

const _Kind_name = "OtherInvalidItemInvalidOperationPermissionIOExistNotExistIsDirNotDirNotEmptyReadOnly"

var _Kind_index = [...]uint8{0, 5, 16, 32, 42, 44, 49, 57, 62, 68, 76, 84}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
