// Code generated by "stringer -type=API --linecomment"; DO NOT EDIT.

package manager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plan9Protocol-1]
	_ = x[Fuse-2]
}

const _API_name = "9PFuse"

var _API_index = [...]uint8{0, 2, 6}

func (i API) String() string {
	i -= 1
	if i >= API(len(_API_index)-1) {
		return "API(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _API_name[_API_index[i]:_API_index[i+1]]
}
