// Code generated by "stringer -type=Namespace -trimprefix=Namespace"; DO NOT EDIT.

package mount

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NamespaceIPFS-1]
	_ = x[NamespaceIPNS-2]
	_ = x[NamespaceFiles-3]
	_ = x[NamespacePinFS-4]
	_ = x[NamespaceKeyFS-5]
	_ = x[NamespaceAll-6]
	_ = x[NamespaceCombined-7]
}

const _Namespace_name = "IPFSIPNSFilesPinFSKeyFSAllCombined"

var _Namespace_index = [...]uint8{0, 4, 8, 13, 18, 23, 26, 34}

func (i Namespace) String() string {
	i -= 1
	if i < 0 || i >= Namespace(len(_Namespace_index)-1) {
		return "Namespace(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Namespace_name[_Namespace_index[i]:_Namespace_index[i+1]]
}
