// Code generated by "stringer -type=LockType -trimprefix=Lock"; DO NOT EDIT.

package mountcom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LockDataRead-1]
	_ = x[LockDataWrite-2]
	_ = x[LockMetaRead-3]
	_ = x[LockMetaWrite-4]
	_ = x[LockDirectoryRead-5]
}

const _LockType_name = "DataReadDataWriteMetaReadMetaWriteDirectoryRead"

var _LockType_index = [...]uint8{0, 8, 17, 25, 34, 47}

func (i LockType) String() string {
	i -= 1
	if i >= LockType(len(_LockType_index)-1) {
		return "LockType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LockType_name[_LockType_index[i]:_LockType_index[i+1]]
}
