// Code generated by "stringer -type=LockType -trimprefix=Lock"; DO NOT EDIT.

package mountcom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[lockInternal-0]
	_ = x[LockDataRead-1]
	_ = x[LockDataWrite-2]
	_ = x[LockMetaRead-3]
	_ = x[LockMetaWrite-4]
	_ = x[LockDirectoryRead-5]
	_ = x[LockDirectoryWrite-6]
}

const _LockType_name = "lockInternalDataReadDataWriteMetaReadMetaWriteDirectoryReadDirectoryWrite"

var _LockType_index = [...]uint8{0, 12, 20, 29, 37, 46, 59, 73}

func (i LockType) String() string {
	if i >= LockType(len(_LockType_index)-1) {
		return "LockType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LockType_name[_LockType_index[i]:_LockType_index[i+1]]
}
