// Code generated by "stringer -type=Namespace -trimprefix=Namespace"; DO NOT EDIT.

package mountinter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NamespaceNone-0]
	_ = x[NamespaceIPFS-1]
	_ = x[NamespaceIPNS-2]
	_ = x[NamespaceFiles-3]
	_ = x[NamespaceAll-4]
	_ = x[NamespaceAllInOne-5]
}

const _Namespace_name = "NoneIPFSIPNSFilesAllAllInOne"

var _Namespace_index = [...]uint8{0, 4, 8, 12, 17, 20, 28}

func (i Namespace) String() string {
	if i < 0 || i >= Namespace(len(_Namespace_index)-1) {
		return "Namespace(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Namespace_name[_Namespace_index[i]:_Namespace_index[i+1]]
}
